"""add_interview_analysis_and_indexes

Revision ID: 995b61f78667
Revises: e82913a9106a
Create Date: 2026-08-22 20:26:55.723583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '995b61f78667'
down_revision: Union[str, Sequence[str], None] = 'e82913a9106a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('job_descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required_skills', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_descriptions_created_at'), 'job_descriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_descriptions_id'), 'job_descriptions', ['id'], unique=False)
    op.create_index(op.f('ix_job_descriptions_user_id'), 'job_descriptions', ['user_id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_created_at'), 'resumes', ['created_at'], unique=False)
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=False)
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('speech_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('words_per_minute', sa.Float(), nullable=True),
    sa.Column('filler_word_count', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speech_analyses_created_at'), 'speech_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_speech_analyses_id'), 'speech_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_speech_analyses_user_id'), 'speech_analyses', ['user_id'], unique=False)
    op.create_table('interview_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('speech_analysis_id', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('clarity_score', sa.Float(), nullable=True),
    sa.Column('vocabulary_score', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['speech_analysis_id'], ['speech_analyses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_analyses_created_at'), 'interview_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_interview_analyses_id'), 'interview_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_interview_analyses_speech_analysis_id'), 'interview_analyses', ['speech_analysis_id'], unique=False)
    op.create_index(op.f('ix_interview_analyses_user_id'), 'interview_analyses', ['user_id'], unique=False)
    op.create_table('resume_job_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('matched_skills', sa.Text(), nullable=True),
    sa.Column('missing_skills', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_job_matches_created_at'), 'resume_job_matches', ['created_at'], unique=False)
    op.create_index(op.f('ix_resume_job_matches_id'), 'resume_job_matches', ['id'], unique=False)
    op.create_index(op.f('ix_resume_job_matches_resume_id'), 'resume_job_matches', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_job_matches_user_id'), 'resume_job_matches', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_job_matches_user_id'), table_name='resume_job_matches')
    op.drop_index(op.f('ix_resume_job_matches_resume_id'), table_name='resume_job_matches')
    op.drop_index(op.f('ix_resume_job_matches_id'), table_name='resume_job_matches')
    op.drop_index(op.f('ix_resume_job_matches_created_at'), table_name='resume_job_matches')
    op.drop_table('resume_job_matches')
    op.drop_index(op.f('ix_interview_analyses_user_id'), table_name='interview_analyses')
    op.drop_index(op.f('ix_interview_analyses_speech_analysis_id'), table_name='interview_analyses')
    op.drop_index(op.f('ix_interview_analyses_id'), table_name='interview_analyses')
    op.drop_index(op.f('ix_interview_analyses_created_at'), table_name='interview_analyses')
    op.drop_table('interview_analyses')
    op.drop_index(op.f('ix_speech_analyses_user_id'), table_name='speech_analyses')
    op.drop_index(op.f('ix_speech_analyses_id'), table_name='speech_analyses')
    op.drop_index(op.f('ix_speech_analyses_created_at'), table_name='speech_analyses')
    op.drop_table('speech_analyses')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_created_at'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_job_descriptions_user_id'), table_name='job_descriptions')
    op.drop_index(op.f('ix_job_descriptions_id'), table_name='job_descriptions')
    op.drop_index(op.f('ix_job_descriptions_created_at'), table_name='job_descriptions')
    op.drop_table('job_descriptions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
